### ISSUE TITLE
Keyboard hides text field on seed import screen

### ISSUE THREAD

**Issue by LukasND** [nano-wallet-company/nano-wallet-ios#18] opened 2018-06-27 20:26 UTC
Can't tap the textfield to paste the seed when it's hidden.
Also, it might be better to disable third-party keyboards for entering the seed

**Comment by zackshapiro** [comment] 2018-06-27 20:31
3rd party keyboards aren’t supported currently.

Best,
Zack

On Jun 27, 2018 at 4:26 PM, LukasND <notifications@github.com> wrote:


Can't tap the textfield to paste the seed when it's hidden.
Also, it might be better to disable third-party keyboards for entering the
seed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-ios/issues/18>, or mute
the thread

**Comment by zackshapiro** [comment] 2018-07-02 22:36
Duplicate of #10

**Closed by zackshapiro** 2018-07-02 22:36 UTC
